### ISSUE TITLE
for removal

### ISSUE THREAD

**Issue by The12GaugeGroove** [BenjaminFaal/TwoPlayerMod#2]
sorted into categorized issues, sorry for the confusion!

**Comment by BenjaminFaal** [comment]
Please separate each issue and I will start working on them when I am home.

**Comment by The12GaugeGroove** [comment]
Separated and sorted, sorry for any confusion!

**Comment by BenjaminFaal** [comment]
Thanks! see https://github.com/BenjaminFaal/TwoPlayerMod/issues
