### ISSUE TITLE
v1.3 - Sluggish/Unresponsive Player 2 On-Foot Controls

### ISSUE THREAD

**Issue by The12GaugeGroove** [BenjaminFaal/TwoPlayerMod#3]
As of version 1.3, driving functionality for player 2 (controller ped) has improved significantly. My friends and I have had an absolute blast playing with this already, however:
- Two controllers are still needed for the mod to function properly, the first controller made to sit somewhere unused while player two uses the second controller (which, if the user has set up his scripts properly, should work). Player 1 at this time may only use the keyboard, leaving the first-player controller untouched (as it will cause whoever uses it to control both on-screen characters at once). The controller PC driver provided with 1.3's download didn't seem to do much to fix this either, despite Benjamin's good intentions.
- Unfortunately, **on-foot movement** for player 2 is still hardly functioning, with mostly severe delays and miscommunication between joystick input and which direction the pedestrian player 2 controls walks in. A debug feature that prompted player 2 to slide forward with no animation (but still at a faster pace than walking) using A has been removed as well, making the already near-impossible task of simple on-foot movement even harder because now player 2 must time a jump in a direction and spam it that way, as the constantly-spinning pedestrian he controls doesn't really decide on much besides small circles, even with analog input.

**Comment by BenjaminFaal** [comment]
Im currently working on this thanks for the detailed description!

**Comment by BenjaminFaal** [comment]
Both fixed!

**Comment by The12GaugeGroove** [comment]
Awesome! Thank you for all your work. I'm putting together a sick video for the script to show it off properly: Would you like to be credited as benjamin.94, or Benjamin Faal?

**Comment by BenjaminFaal** [comment]
Wow man that sounds good, please Benjamin94.

Please wait for when its done.

**Comment by The12GaugeGroove** [comment]
It's alright, my video should wind up showing it off properly regardless. It's uploading now and should hopefully be ready to go alongside 1.4's approval on 5-Mods. Hope ya like it!

**Comment by BenjaminFaal** [comment]
Hey man very nice video! Could you do me a favor and make some sick screenshots as well which show the menu and gameplay.

**Comment by The12GaugeGroove** [comment]
Sure thing man! I will take some for you tomorrow in the Rockstar Editor etc with my brother once he gets home. Stay tuned!

**Comment by The12GaugeGroove** [comment]
Alright, my brother got home so we'll be playing soon. One thing I will mention, as I've only now noticed it and it seems many others still haven't caught on:

In v1.4, player movement has continued to improve and is definitely playable in its current state, assuming you know how. This is not the case for most people, who will endlessly spin their player 2 in circles with no clue how to do anything else. For those with this issue, simply tell them this:
- The left analog stick is **very** sensitive to turning
- No matter what way the player is facing, **left-analog movement "UP" will ALWAYS move him forward, no matter what.**
- This means, even if you'd like the player to move diagonally-right and down, you must **lightly** move the analog stick in whichever direction, **then move forward properly using left-analog "UP" no matter what**.

After realizing this, player 2 is able to control his movements far better and once he is moving forward using "UP" on the left analog stick, walking in different directions comes far more easily.

**Comment by BenjaminFaal** [comment]
Could you retry with version 1.8 and report back here?

**Comment by BenjaminFaal** [comment]
This should be fixed now, if not reopen it please.
