### ISSUE TITLE
Camera Suggestions

### ISSUE THREAD

**Issue by The12GaugeGroove** [BenjaminFaal/TwoPlayerMod#5]
- Of course split-screen isn't possible so I won't even daunt you with the task. However, perhaps a way to zoom player 1's camera out much further than usual and lock it in an isometric-type view may work better? For example, watch this video to see how Rockstar themselves did it in GTA: San Andreas. Again, I'm not tech-savvy such as the developer, but a system like this seems much more doable compared to actual split-screen (which in itself goes against all of the core RAGE engine's rendering possibilities): https://www.youtube.com/watch?v=3HEY1svFQIA&t=75

**Comment by BenjaminFaal** [comment]
Added experimental custom camera, please take a look at 1.4 and report to what needs to be changed.

**Comment by The12GaugeGroove** [comment]
Very nice! Much better than the normal camera, however the problem of turning the camera around is an issue now.

What I would suggest, if making the camera rotate on its own is too problematic, is a sub-menu to allow the players themselves to rotate and zoom in/out the camera if need be. Maybe another way would be to get both player 1 and player 2's front-facing headings, and if they're similar in value the camera could rotate to face forward for both of them until they're facing opposite ways again, which would cause the camera to stay locked in its current angle until both players move off in the same direction once more.

**Comment by Jitnaught** [comment]
@The12GaugeGroove I added a GTA: San Andreas style 2 player camera in [my pull request](https://github.com/BenjaminFaal/TwoPlayerMod/pull/8).

**Comment by BenjaminFaal** [comment]
Thanks @letsplayordy nice work this issue is done right?

**Comment by Jitnaught** [comment]
@BenjaminFaal I think so.
