### ISSUE TITLE
Player 2 Combat 

### ISSUE THREAD

**Issue by The12GaugeGroove** [BenjaminFaal/TwoPlayerMod#6]
Combat availabilities for player 2 (besides running people over) are nonexistent as well, presumably due to the major task of implementing such a system into the game for a separate player to utilize as well.. Maybe there could be a way for player 2 to force his ped into a "combat" mode of some sort? Something like a quick AI behavior that essentially turns the player 2 pedestrian into an AI bodyguard that protects and fights alongside player 1 until the mode is turned off? Maybe another similar mode that just makes them attack whatever target entity is specified beforehand? I'm no tech wizard so i don't really know what is possible, and it wouldn't be perfect, but at least player 2 could have some sort of fighting chance this way or one similar, because if they're backed into a corner against some angry gangsters, they will endlessly get their ass beat.

**Comment by The12GaugeGroove** [comment]
I noticed in 1.5 you can now select different weapons using LB + Right Analog. Is there a way to fire them as well?

**Comment by BenjaminFaal** [comment]
Hey you noticed that correctly, not yet I'm still trying to implement a nice way. But I think it will be possible.

**Comment by The12GaugeGroove** [comment]
The new combat method is great. Can't wait for proper melee behaviors as well.

**Comment by BenjaminFaal** [comment]
Yeah I still need a way to figure out all melee weapons, If you want you can help me. 

Pick all melee weapons from here: https://github.com/crosire/scripthookvdotnet/blob/dev/source/scripting/WeaponHashes.hpp

Just the names of the weapons like they are in that file.

**Comment by The12GaugeGroove** [comment]
-           Knife = 0x99B507EA,
-           Nightstick = 0x678B81B1,
-           Hammer = 0x4E875F73,
-           Bat = 0x958A4A8F,
-           GolfClub = 0x440E4788,
-           Crowbar = 0x84BD7BFD,
-           Bottle = 0xF9E6AA4B,
-           SwitchBlade = 0xDFE37640,
-           Dagger = 0x92A27487,
-           Hatchet = 0xF9DCBF2D,
-           Unarmed = 0xA2719263,
-           KnuckleDuster = 0xD8DF3C3C,
-           Machete = 0xDD5DF8D9,
-           Flashlight = 0x8BB05FD7, **_(?)_**

**Comment by BenjaminFaal** [comment]
Thanks man, i will try to find a way to make it work with melee attacks!

**Comment by BenjaminFaal** [comment]
This seems almost impossible unfortunately, there is no native way to let a ped fight melee...

**Comment by The12GaugeGroove** [comment]
Do you think you could simply force simple melee animations (and a forward force if the animation alone won't suffice) upon the player 2 ped with pressing B? Even if it's as simple as one type of punch or kick.. Anything is better than nothing. Great work on 1.9 regardless, the length this script has come in such a short time is absolutely amazing. 

By the way, here is a link to the mohawk used in the screenshots I took. I had seen someone asking in your comments for it: https://www.gta5-mods.com/player/recon-cut-for-franklin

**Comment by BenjaminFaal** [comment]
Melee weapons are working now too.
